version: 2

sources:
  - name: backoffice_db
    description: 'All data in our backoffice.'
    database: backoffice_db
    schema: public
    tables:
      - name: company
        description: 'Details about companies registered on our platform.'

