
version: 2

models:
  - name: example__my_first_dbt_model
    description: "A starter dbt model my_first_dbt_model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: example__my_second_dbt_model
    description: "A starter dbt model my_second_dbt_model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: example__league_details
    description: "All Football leagues and their respective code"
    columns:
      - name: name
        description: "Name of all football league"

      - name: code
        description: "Code of all football league"
        tests:
          - is_french_league


sources:
  - name: backoffice_db
    description: 'All data in our backoffice.'
    database: backoffice_db
    schema: base_dbt
    tables:
      - name: league
        description: 'All Football leagues and their code'
